[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/studio"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/studio/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/static/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/robots.txt"
  to = "/static/robots.txt"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap.xml"
  to = "/static/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/post/*"
  to = "/static/index.html"
  status = 200
  force = true
